---
kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/melinda-record-load-rest-api-bridge/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    script:
    - "cd /exlibris/linnea/melinda-record-load-rest-api-bridge/app/"
    - "npm install"
    - "npm run build"

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/melinda-record-load-rest-api-bridge/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    script:
    - "cd /exlibris/linnea/melinda-record-load-rest-api-bridge/app/"
    - "npm install"
    - "npm run build"

trigger:
  branch:
  - test
  event:
  - push
---
  kind: secret
  name: host_test
  data: wTd7hNNzXvIAbcLcdh+v2nJah6v+FaqzW+lh1JGsIneq8uC6iDwFOezZkwwm
---
  kind: secret
  name: username_test
  data: m5NHENJ7mevnkpbyMjOrrB7XJMet55n8p6FRKeom4BYa
---
  kind: secret
  name: ssh_key_test
  data: 6uab9zwI8L8YhByTUQfgmkSimqv8ezxc5UWuyS4x69DLqBwgtS4P9YazrHgyy9RvkxWpem16kDUZW0pMVASdHkw6BW28lon8ggyDh4FweqqxOSfULZ7Y8YEmz1W5UqYDlzNbN+BBCATAjOLPrFuq7nzhV93Dw4SvhmCZ8dtOLc0qscbdHqmH/i6fwOXauRyUQDgM5Eqcx5yT7scz1P9scmKq3WEFwjDDZeLhPY9Ox55tJOXQKT9rXIYSDtMrmBkVMgCZiQWj9F7Cx8wRvntCTTWcF+Rr+2jbEbnGXR0qNMdPTZuLbI4Xn0WBSId+V+LDUO4wbE69ZY63h+Gj5/g4hSkYK+scUvWQ1tmsVqAtLVDCUXZHqs35wkDIizdRezk0SA9nW+npHRzs7mLA+Mrq48TbGeiVCLaqeuhSh9Bp+MPx5MaSPbjUeV5O3vkK8d3UkKvSSuvAqi4D4Kwis1qIumEB+KsxP2BbueRnfhVgInbMQ1wykpJmlfUdjUedHM07WPDVyT5sQC/CBeSQtVNUE8qurYY7zFoCcbYKKWXVdqrqZUoiAB1c/mJUiF/bjmOc6MuimKIpQceHR5/m0wl2SQxXsN80LbkVWDcZoV/7Lm7X4IsKfJzyJ5UVZVvkeWGf0SFsLNTTrvnLuGqwCGKoO53UDlkIN0tOXaXk7GV3Rh++RkNLr2ATr4aQ6zDLTVJRlyDYRTl/P5BzM9tkfbSaf+WuUlMmF+gPS97Xtfpk6NN+mql4qRYTBACjrsd9wSp85SOfdpFnyyTAIcCUMZX+2gnnjMsiH3rzGW1iGDzYTHu9OkIuI6IxLw/JHJp4/fwu2/zU2tQBxKLjYJyxX32ky+M0Cl2DXl9TMbrE5c8aF51CUmJbcOU6BUqghB+s8YcLSVZtH+YROfmO42IPeKtM3A4Wlr9mFsPYgzZmdG4iCZC8osC6BeZtk6Sqmxyf/Rm5dtKMTZFQnd5DxgsXxB93XqUtt749mv/d+axtlfPb7ez9PsYXQZ6VW+SOUAgx8epi1ZQVP0Oqa8w5nQEhhgRTD+vTeNlS3HVIPtt/dXq5pHddpYJ2oWu+7XOE/hjeDe1FdExkf5pyV0Mk3CV5Z8PgUrTXmUP8FmhYfthU6ovbZNx4HvuuvoDTWCb62TABH89iQNAtB68crNxJkCZX95lBZ6Tqwl8Qw/+s23r9X+EiycAEF02Kf9cPr1HEJy4k+DZSdf1i+GUW7/9JJTV3NJoQSUoD1MBeAQGeD//iRc8ajQPL+EWzAr5gWjUmmkpof4qY5yek8XQ1fRP9RmlqIVc69ebao9xXksto7V05DpmBg5Q1FxJ9GlO6tXNZPoPy6uOfqfGeqUxJIjhgsqeJhjtLPdt873c24YuoHH3JV3CJdV5DMWNdA7387Eg5wmNZz7xiCrGRYPl3OtYbaAAuS8TZOOqoEqfEwY/dh+xq1rqKd6PrN2hho9PsWPEbUhx23hhPmOjmdz7GSnSacsxHmH8FaiGRQJen51sCDyNqXcIm3l5cHk0px1E3SRHJlHO7hdDdDtuYeG0mMtvxSRKfV/ScIp5w61CfOX1hQ1wSEGN4j7o3IuOswO3zxFqXvdrAeGU2gIXvcJRIxXmR9werj3vYUE5AQeUxUUBuZuz69/KX2xary1h+U/nAqZtNFXEJVpL+pwIDzU1j+cRK1QetGulgtcaYzgiyzcEKhX/uX0f46KJ8A/zNDwwsivo4F4+443Duf+le16DfwxrUmsoeKoHFSDbq/MQzA1UwAzwCnptBpmXG/t0h8AcuWD8Ls44nQrgdT2mS7azPCK4I4j+7KMh8OC8qAfdP0U/53onxloRU1a6U4u1cXCjpppaRYfd8PJjnUXZ4HYoy61uv9MneW3Jvd7gyM7fuB3RIs8u8oRboNdYPEMuKI05Hhi0/GlD2NsBaHIQ3vlb/O3iZMHx6whlb8C19l340R2ANJ0uYc3b7CECl/6Mli+7H4eoQY1boq+QspthBG4okjL6tp3MCQ+CsRX6LZoxlJNMw3ocmA36WhtiPC8JXOpQMSQ3/KkGLjuAn3DSbhsuFBu3CZIKiannckeijb5mETwZeHfMW+pwq3lj8sE5gzpcUwYxavPSKZopM2xvhOhGHT6FL0glW8fjY/A3WiM9bc1e8P0km6nxFa7/Vh/aa5NF9kY8klO0Z2H/QHjro5SiJDfIApIBbtj0fM/F3P41KWGluAVfafKiJZwf2wSOCJjsq1Hk+dLBL7rvBe5dnRNIVxvinmYbMEruaCOLtGj5ZmmvMcT7z

...
