---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --production --audit-level=moderate

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  - name: check-coverage
    image: node:12
    commands:
      - npm run coverage

  - name: build-production
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production
    when:
      branch: [master]

  - name: build-test
    image: node:12
    commands:
      - npm run build:dev
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production
    when:
      branch: [test]

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: prepare-for-deploy
    image: busybox:1
    commands:
      - mv node_modules dist/
    when:
      branch: [master, test]

  - name: deploy
    image: quay.io/natlibfi/drone-plugin-scp
    settings:
      rm: true
      source: ['dist/**']
      strip_components: 1
      target: /exlibris/linnea/melinda-record-load-rest-api-bridge/app/
      host:
        from_secret: host_${DRONE_BRANCH}
      username:
        from_secret: username_${DRONE_BRANCH}
      key:
        from_secret: ssh_key_${DRONE_BRANCH}
    when:
      branch: [master, test]
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: host_test
data: powwHniDb9zkmHRXaZRoQIz7b/g9eBGPF3KblVk+GknBcpwdEH4iaOs/9iHX
---
kind: secret
name: username_test
data: 9pANJwrFOaVJJ9hP6vudztgtSEzAlxDlsqbqJJlbA78G
---
kind: secret
name: ssh_key_test
data: 2oNbEXydn7LXKpRlTHz3b5xXONaGzrb36JNbBsNJhbrpkA7Ije4CRiHr/woFewJNNAD0Xi7db+6owowWyXlLogME8n0s5DlKjFE283G4cORuffair6Yxno8l9wajh+UL7ataDruXfaEB8bvu7guCzrZ6bIDH5Kc+MIVMmDVMQRkOyDkvQJXWWlgWvSdGcz+pE5Ev0or8S/4EhFhDdgZiAeBPfvSH9hpt0eAvgTmMrjpSuWyzrIdWHV0u+vm5xSS0ZhB84tDS1sPlslQkRmjjry5M6K0iwHy+ApExEAdNTYthAauNj2YSxgSoB7Ec1tFFN9coypwyMUXCLNwVeJJ14fjdFLne3l7Un7S0XZFzMDqe6dR09+4GVFBySkQ2IzkPSEDgyBOxWSNo76DPF1j4jRDRk3al0ryj7O5P/g9t25hIaZoNaEdDY8Vf5G6bjrGNqD42oYmM0v93phpgQtJcsG5XajYElOEZwwAjUVv/bscmc5zc6ULc0Vc+dYuWfTpCocPzZV11psBNNaj8VO8+gAP2Ga1add5oALV6XT7gEJDrf+BoD/5wzVkoMF3m88vHfG02vu4luzT0GnFaf1gCHEnUG0bAvT3GZS0K+0zBRYXfnigSQu72+HVFpPxUDS6o/oLoZkIUTxj4bWcMIaOG+I6NLdxej7VjkAR+hwNf8vYfQOn5it3LDNcN3e9NU3UTQsEr2rZf8G7EquWL/kv6+62FbRvEVsmgZsi4qzYYMfgnvr4yjOVvMCLxcqgkAKpFz4sTi5tMD23sDuCBe9Mkb6TO77Jnf9tu3Qh4NS2V2bqYnyZ/XrfrHQNrq9uCbqZC+OSBvYpOPUrILbQaytCswR66XHrKJ1VbCcM3ZOgJ5nmJSYnxdHhRdSp/EqJAyu58fJ3RM1X/k136H00CErelujJGFz1ShTS2457HbLczjrAi0VG1rs/O92eeV8wn3onAJmy8Sbhk3icy+8gduFv1yG4p+2luKjIJcIGvV2CzNK4GFv5EONrVaxSu2Ty+387y1ci1AeZEcT52qenuYLYTORY3cUA9T95vQesFrtKVzosRQC/nI2IiOtcumuLNCeLvxnk9h4ZJdTqRnGEFSsDGdTwOLgDV7JcXBoRHlt8rZRfdTQ8qw3whvkpPoFeKQJoIcq5FqyKs9ScNesLNCznHE03XdY5E06yAgO9xIJdGtZ8D8mgafrfQuJmZNbIJExZCg5n9MODyQQDTmUQ4/5E5ZD8u5K46t8Dem9ZZZbrkHYvU+16c6lBsix9z7Uzz3bVwfvk7RrVRDH09M4aSPc2bhctXz70hqSVzMeCBpklswBpupEuv3OT0NM1pg9MyGOirqHQQZIPVHQ1aI9zZVx0GbWErscZZTbb/Bpm3KiAU+X52qwpi2Oi6t7qMYwZ3zab5DDrsQkRdVaoNgZno7CXQ2zF46NufqfT8p98A69O0k/bs0D55CzmFyuZWa6Y0zKtFTlMRiuCv3wKwVSb9buLPlEd2DjNUtPHflJmXkgtBmcuCZCRVQHW8i1uUca2MSzOmGXUjFN3w7QcldgkrvS85YeJDV2lXO1ZrL+ZsOhZDeDzmg1FHa7odpCIir9ikyOYl858JJ+EJcdw+vyt+MqBNCQqUV+zuxQlrlQqwUfwuqT4LolnQelFjm/Rkc6FK47f8OlRnxPzXbrrVvDvGx0A8OhKP1JTMCNW31XOVptHd86LbJ22nVYLED9f75cnKNfY+ulOAFPJCYZhrThfOxfP3KP/yZBEpyoXvO9XRr8S3FEIecyKvlWe71BoJTRUWWWHdUTJSkby9zN7cYYiLFShFjDAD5eOxNBTcwWDtd5OPo2YgmcP6YQ6yGNvcrn1i/CgNPgIBU1Hqg+c0/uFodn24i2UEF/D2vXiCS59miQC5qcSQ1sIHWRM/4WDS8SO0YD+B69tifAp3bxGlvDrrPI8/+Iq77i9+wf32JCLi0V4Db4D79LRApsORhUYt5G6Bhbqs8xTZvg9I/tYlTW6kFtOLrbXAbJ/nVOq4rWi3x3hrirAy/joMFcX6I9xytAmtvJ6L210/jM6zkxwEIJFS2d8tm0swtYNikTe9Rj24Wrxy/RyQ9sOzFVbezHLEgJoGQ+tiKrz3bviBW3FxJWa+6/71fv0XlJGsTBNQh89gfYHqjMGZux/pGvZJth6+K6bC4QSRb6kHzaCOokvcONtoslhkFs7ydoL896lrAOqLku3mxUnpeahNLgufQlQah1nqJkuVoZfriKzEfQFa3NL6Rfgw3PE++J4P+iM=
---
kind: secret
name: host_master
data: nQKhYDoAnohjPcr1o/LtF2d+DHTrmdDjvNvWhN3GEfD/Vr/fr377rgdgNrY=
---
kind: secret
name: username_master
data: 2CY5Tf1uvLoA4pGoKs75JhXLAs/khLHO+hjhdPHTtq7H
---
kind: secret
name: ssh_key_master
data: Ly4htjCg+GC/bc28dOtzrB0iwCeeE0VXeTcyiWmfB6+qW+cmLhRSY01tDXxkjO8ClOx98RPuK1EOkBCjcizQa7hJU1F4h22jfeKwb8UbrA2ovXbzIzBOufPcC5YFm57MOXfDvCQr14D62ryQycinp8G6FCkwm3casZZ73PGhxK+rZrmopHiL5zc7saP7o65Wq2mla4urAdTQkBkV7lUPPm/4vtAXc6Dm1Tup6/IT0RyojVEAd8FTNOKJAr5haduFSAFBq8Hj3+XcinzGFtxnBO6GN7mv7eLP5kd1faCPsfvzE/ziQYVpD18mz571V0lh84iUuiP5YtIwqJErxqus8VZMpGrZW8+eAquQPiP4gHy9yQcu01XjcD8f0jkMF9auLR39oFsBW0rqZOuZTu49P2uP/VZXh0JQ2mEmKOw8drjd34sotewLFS2ON6FrGHmRp8mddXkMd3nXQVJ+GoP1ZCYrwlLfGbu/7TUT1E30/NuSkxgaFf5j9LTVKUwZL5gJzzhONQ841fceocxyR/6AejwP7qoROsyipVxvqLqewQjQyvWJYPUifihXFGtEHSXZIBUKlkPUOgiU0cHVeVtqEan3+2IJShwABau9R5133gPAMcEKkAltsgeEKNIyD5Nv/D+pahSMoPO7TZ3Kj5ZkSTGWw3gun85Exb41YCtpecYlfSZG76fMFFGm9TrpboTLqzKct9JI1DhI7cNCn1m0pmWuTV03IAZ9lxb/f0+aJBckDgxN1c4b1t1ejXWX0O5VVzpV8J3QW42oW2tjNd+HfVLeZMyT6+0qfrZ1gZO/mEGAITxn6IsaT+cQq7W0eyg/FN0SgtgGfje5Zw3Ji8w5fswP/kbLuJ9ocBZZwdSsBYaEAiNIEOHOubFG5/MJn8yGMWDll0ZY7ZHL5mGUL7rkyziEkHP/l0sPbA6GkU+pRadnWGu0xJ0ySP+fDQwrmt1yr5LtYjOM83OwAVOtST6OXxBw2w6eqPYCv5wNW/Tce16+5U1ixpcFfaI5pJuWss2eLmfaNx4H/BgicnouQWjKzr1mzPfPpxQYQWgkxXbpdRInWWsU1qpsar4TEO0NnyvRu4hH9cBrqnSn5UY2un06O8Veuyj/dexjNVkhhEEzuKOsANDh4ADC7jHJEwTB4fUXBW2bqo7a5Z+GwrtQxNgb0+leBmG8OVD/fvpFj6Skhp6OMnALJpmRup+x0GaJkoFTzcSc2nj2AuY7Y00HlPFmRc8KJnWdJiMkjDvNgw2qbVjt9Ve4IrDiyghyJ9cKAbxvZAOdQ81xs0v/T4nyZKjZ7mEc+DESWQzkJ4zNcJDH8Pz8e8WzhIQZh79n4iz8a7M9gnfUQ1Wwhx2uXdT5F8o7JhJvIuELZ0R0VZWDmD2a0aJ2zZbLX5I0kPhzNYoYk0B+k8n3pWdOsgHh8XHlZVfkM4TuOIZcXhnmQ/BBzD0buUnxxINIllrNup6ZMjlJz7KOAVg0L5I2XFZGz4+P9ESo2bJO6rKIvRTmWjgr7qAzxRVIUc9vZusyUFD9RuoQymAM28mS7I2Mhsk9Cd8pqrZ6MKuwy4vxjQBiiJDl9chC2m+Qnr4g1CK13yRoDUhWhzuwfv7EPJUfrxnoyIP8RKhPpY+h7c5e7+iJ6maMcUv/ZzKH6IXouT9zNWGIldJA7kSnmZa2NBRUu36c/rtWqMIj/Dxai8CBOdnkWcwfRlwuY0w+6bSHgR8+XBxz8OcQvttlK8D/zZIb0E605nmSdVCo93W6oZ85kFJMBErKk0lRMiu9EZ6ZCuhDGiZ2vnsxyPsHSWKEY3119fN6C1SzOpUezo3/DUK5+5JmcnEBqQ8b/UBvc+dEIYgb4bOdCyxDJygSOzqawxaZA4I90GB3j4kpAtpFfFfBQFcTG15suIG+T7PdlvXSKXe6MmSciUfd2UeB9tEVjRqado66dkTbbWQ0ToOQMeZS0yELOonf0xU7YSwBcaibpcXJtpb1j19xYOPmlV8X3bN5VxPFgQJ2PVNwdxkl8fcWlXwRlcEui7jQxLsQSgJOE4UtC3Ur3Zjjiw/51+y72Vzsf144qSZ+pYbtxC33AbyW9pYPpN+63Vl50V2ittj4WsfA0sgmv2W8EWc9O4pbq4bNRXBiiPoxTiAW8SazQn8NNXlJ497ITwH3YxV2vQiGcuy0HPQuZlIO7ljA9wFNwuwU8Zct/YPgXmvQBTt/wfe2L54/mh+wR9CAgMGgQI2STWY/OrkLW9nYs87g8+ldYb5WDUfKMfqj1Tf9kUsO2W4LFZM=
---
kind: signature
hmac: fb63962c07e0d27c134813f4cf3c65df3cf7e0241a38de90923d9ce114a644e8

...
